# This ArgoCD Application deploys the ClusterSecretStore to the EKS cluster
# The ClusterSecretStore is responsible for managing secrets in AWS Secrets Manager and making them available to Kubernetes applications via the External Secrets Operator.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ChukaOkeke/restaurant-api-eks-gitops.git
    targetRevision: HEAD
    path: manifests/addons