# This ArgoCD Application deploys the External Secrets Operator via Helm to the EKS cluster.
# The External Secrets Operator is responsible for synchronizing secrets from external secret management systems (like AWS Secrets Manager) into Kubernetes secrets.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Source 1: Official External Secrets Helm Chart
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.9.18
      helm:
        valueFiles:
          - $values/values/addons/external-secrets-values.yaml
    # Source 2: GitOps Configuration Repo for the values file
    - repoURL: https://github.com/ChukaOkeke/restaurant-api-eks-gitops.git
      targetRevision: HEAD
      ref: values