# This ArgoCD Application deploys the AWS-sigv4-proxy to the EKS cluster
# The AWS-sigv4-proxy is responsible for enabling OpenCost to query the Prometheus (AMP) endpoint

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost-aws-sigv4-proxy
  namespace: argocd
  annotations:
    # Set to Wave 1 so the proxy service exists before OpenCost (Wave 2) starts
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: https://github.com/ChukaOkeke/restaurant-api-eks-gitops.git
    targetRevision: HEAD
    path: manifests/addons/opencost