apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: restaurant-api-instrumentation
  namespace: restaurant-api
spec:
  # Target local cluster OTLP HTTP receiver served by the traces collector.
  exporter:
    endpoint: http://adot-traces-collector.opentelemetry.svc.cluster.local:4317

  # Cross-service distributed tracing propagators
  propagators:
    - tracecontext
    - baggage

  # Sample 100% of incoming traces
  sampler:
    type: always_on

  env:
    - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
      value: "aws_lambda,aws-lambda"
    - name: OTEL_SDK_DISABLED
      value: "false"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "grpc"
    - name: OTEL_RESOURCE_PROVIDERS_AWS_ENABLED
      value: "true"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_METRICS_EXPORTER
      value: "none"
    - name: OTEL_LOGS_EXPORTER
      value: "none"