mode: deployment

image:
  repository: "public.ecr.aws/aws-observability/aws-otel-collector"
  tag: "v0.40.0"

serviceAccount:
  create: true
  name: "adot-collector-sa"

# Explicitly disable chart default presets
presets:
  logsCollection:
    enabled: false
  hostMetrics:
    enabled: false
  kubernetesAttributes:
    enabled: false
  kubeletMetrics:
    enabled: false

config:
  receivers:
    # Explicitly set uncompiled default receivers to null
    jaeger: null
    zipkin: null
    prometheus: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15

  exporters:
    # Nullify uncompiled debug exporter
    debug: null
    awsxray:
      region: "eu-west-1"
    awsemf:
      region: "eu-west-1"
      log_group_name: "/aws/eks/asgardcuisines/opentelemetry"
      log_stream_name: "adot-metrics"

  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  service:
    extensions:
      - health_check
    pipelines:
      # Nullify unused logs pipeline referencing debug exporter
      logs: null
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [awsxray]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [awsemf]

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP