opencost:
  exporter:
    defaultClusterId: "restaurant-api-eks"
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      # Dynamically injected by GitHub Actions CI/CD via Terraform output
      url: "http://aws-sigv4-proxy.opencost.svc.cluster.local:8005/workspaces/ws-98541f83-9a89-4bd6-a2f7-52ea501b9117"
  ui:
    enabled: true
serviceAccount:
  create: true
  name: "opencost-sa"
service:
  type: ClusterIP
  port: 9003
