# Overrides default replicaCount for production HA
replicaCount: 3
image:
  # Repo & Tag updated dynamically by GitHub Actions CI pipeline in the GitOps repo
  repository: "618339653656.dkr.ecr.eu-west-1.amazonaws.com/restaurant-api-dev-app"
  tag: "27e1e0e"
env:
  awsRegion: "eu-west-1"
  # Production settings file containing logging and cache configurations
  djangoSettingsModule: "config.settings"
  useS3: "True"
  s3BucketName: "restaurant-api-dev-static-assets-618339653656"
  cloudfrontDomain: "asgardcuisines.link"
  sqsQueueUrl: "https://sqs.eu-west-1.amazonaws.com/618339653656/restaurant-api-dev-booking-queue" # Replace with Terraform output
secrets:
  storeName: "aws-secretsmanager"
  appSecretName: "restaurant-api-dev-app-secrets"
  rdsSecretName: "arn:aws:secretsmanager:eu-west-1:618339653656:secret:rds!db-b2b37003-154d-4bab-aec8-5841ec3b01f6-a1CIZ2" # Replace with Terraform output
config:
  DB_HOST: "restaurant-api-dev-db.cvcmaqucsk7w.eu-west-1.rds.amazonaws.com" # Replace with Terraform output
  DB_NAME: "asgard_cuisines_db"
  DB_PORT: 5432
ingress:
  enabled: true
  className: "alb"
  # Matches the Route53-registered domain name for the ALB to route traffic to the API service
  host: "api.asgardcuisines.link"
  # The security group allowing traffic only from CloudFront managed prefix list
  albSecurityGroup: "sg-060d2bf81e401eb0b" # Replace with Terraform output
  # ACM certificate for TLS termination at the ALB
  certificateArn: "arn:aws:acm:eu-west-1:618339653656:certificate/265fd634-d1f0-436a-9512-3edf3d2491d3" # Replace with Terraform output
# Resource limits strictly enforced for cost visibility (OpenCost) and K8s stability
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  # Aggressive scaling trigger for the booking engine under load
  targetCPUUtilizationPercentage: 60
